-- Q1. What is the total revenue generated by male vs. female customers?
	
    select sum(purchase_amount) as Total_revenue, gender
    from customer_data
    group by 2;
    
-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

	select customer_id, purchase_amount
    from customer_data
    where discount_applied = 'Yes' 
    and purchase_amount >= (
		select avg(purchase_amount) as Avg_Spent
        from customer_data
        );

-- Q3. Which are the top 5 products with the highest average review rating?

	WITH product_ranks AS (
    SELECT 
        item_purchased,
        ROUND(AVG(review_rating), 2) AS avg_rating,
        RANK() OVER (ORDER BY AVG(review_rating) DESC) AS rating_rank
    FROM customer_data
    GROUP BY item_purchased
	)
	SELECT *
	FROM product_ranks
	WHERE rating_rank <= 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

	select round(avg(purchase_amount),2) as avg_amount, shipping_type
    from customer_data
    where shipping_type in ('Standard', 'Express')
    group by 2
    order by 1 desc;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

	select round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_spend, subscription_status
    from customer_data
    group by 3
    order by avg_spend DESC, total_spend DESC;
    
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

	WITH discount_stats AS (
    SELECT 
        item_purchased,
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted,
        COUNT(*) AS total
    FROM customer_data
    GROUP BY item_purchased
)
	SELECT 
		item_purchased,
		ROUND((discounted * 100.0 / total), 2) AS discount_purchase_percentage
	FROM discount_stats
	ORDER BY discount_purchase_percentage DESC
	LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

	with customer_type as (
	SELECT customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customer_data)

	select customer_segment,count(*) AS "Number of Customers" 
	from customer_type 
	group by customer_segment;
    
-- Q8. What are the top 3 most purchased products within each category? 

	WITH item_counts AS (
		SELECT category,
			   item_purchased,
			   COUNT(customer_id) AS total_orders,
			   ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
		FROM customer_data
		GROUP BY category, item_purchased
	)
	SELECT item_rank,category, item_purchased, total_orders
	FROM item_counts
	WHERE item_rank <=3;
    
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	
    SELECT subscription_status,
		   COUNT(customer_id) AS repeat_buyers
	FROM customer_data
	WHERE previous_purchases > 5
	GROUP BY subscription_status;
    
-- Q10. What is the revenue contribution of each age group? 

	SELECT 
		age_group,
		SUM(purchase_amount) AS total_revenue
	FROM customer_data
	GROUP BY age_group
	ORDER BY total_revenue desc;



    
